#!/usr/bin/env python3
"""ArtCNN (https://github.com/Artoriuz/ArtCNN, MIT) mpv GLSL hook -> shaders/artcnn.hlsl.

Parses the embedded weights of a "C" model and emits one cs_5_0 compute shader with every layer baked
in as literals (root constant `layer` picks the branch; fxc takes ~3 s). The models are 2x luma
doublers; the port keeps the output at 1x by averaging the 2x2 depth-to-space block of the last layer
(= exact 2x2 box downscale of the 2x result), then adds the luma delta back to RGB.

Shipped model: ArtCNN_C4F16_DS (denoise + sharpen). The neutral C4F16 box-averaged back to 1x is the
identity to within 1/255 even on a step edge (a consistent doubler's downscale is its input), so only
the DS/DN variants do anything at 1x. Any C-model GLSL works as input (C4F32 = 48k weights, ~4x cost).

Feature maps: 16 channels per layer = 4 quads of an RGBA16F texture at 2w x 2h: channel group q of pixel
(x, y) lives at texel (2x + (q & 1), 2y + (q >> 1)) - the GLSL's own layout, so its weight naming
(inp_<q>_<kx>_<ky>, result<q>) maps 1:1.

    python tools/artcnn_port.py <path/to/ArtCNN_C4F16.glsl> [shaders/artcnn.hlsl]
"""
import os
import re
import sys

LUMA = "float3(0.2126, 0.7152, 0.0722)"   # BT.709 on the gamma-encoded RGB, like video luma


def parse(glsl):
    layers = []
    for chunk in glsl.split("//!DESC")[1:]:
        desc = chunk.split("\n", 1)[0].strip()
        if "Depth-To-Space" in desc:
            continue
        biases = re.findall(r"V4 result(\d+) = V4\(([^)]*)\);", chunk)
        terms = re.findall(r"result(\d+) \+= (V4|M4)\(([^)]*)\) \* inp_(\d+)_(\d+)_(\d+);", chunk)
        layers.append({
            "desc": desc,
            "relu": "ReLU" in desc,
            "binds": re.findall(r"//!BIND (\w+)", chunk),
            "bias": {int(r): b.strip() for r, b in biases},
            "terms": [(int(r), kind, [x.strip() for x in w.split(",")], int(q), int(kx), int(ky)) for r, kind, w, q, kx, ky in terms],
        })
    return layers


def emit_layer(n, L, last):
    out = []
    nres = len(L["bias"])
    scalar_in = L["terms"][0][1] == "V4"
    skip = len(L["binds"]) == 2
    out.append(f"// {L['desc']}: {'1' if scalar_in else '16'} -> {nres * 4} channels, 3x3{', ReLU' if L['relu'] else ''}{', + long skip' if skip else ''}")
    out.append(f"void L{n}(int2 p)")
    out.append("{")
    for r in range(nres):
        out.append(f"    float4 r{r} = float4({L['bias'][r]});")
    qs = sorted({t[3] for t in L["terms"]})
    for q in qs:
        for ky in range(3):
            for kx in range(3):
                d = f"p + int2({kx - 1}, {ky - 1})"
                if scalar_in:
                    out.append(f"    const float i{q}_{kx}{ky} = Yl({d});")
                elif skip:
                    out.append(f"    const float4 i{q}_{kx}{ky} = Fq(src, {d}, {q}) + Fq(skip, {d}, {q});")
                else:
                    out.append(f"    const float4 i{q}_{kx}{ky} = Fq(src, {d}, {q});")
        for r, kind, w, tq, kx, ky in L["terms"]:
            if tq != q:
                continue
            i = f"i{q}_{kx}{ky}"
            if kind == "V4":
                assert len(w) == 4
                out.append(f"    r{r} += float4({', '.join(w)}) * {i};")
            else:
                assert len(w) == 16   # GLSL mat4 is column-major: column j scales input component j
                cols = [f"float4({', '.join(w[4 * j:4 * j + 4])}) * {i}.{'xyzw'[j]}" for j in range(4)]
                out.append(f"    r{r} += {' + '.join(cols)};")
    if last:
        assert nres == 1 and not L["relu"]
        out.append("    // depth-to-space would spread r0.xyzw over a 2x2 block: the 1x result is their mean, clamped like the GLSL")
        out.append("    const float4 c = rgb[p];")
        out.append(f"    const float y1 = saturate(dot(r0, 0.25)), y0 = dot(c.rgb, {LUMA});")
        out.append("    dst[p] = float4(saturate(c.rgb + (y1 - y0)), c.a);")
    else:
        assert nres == 4
        act = (lambda s: f"max({s}, 0)") if L["relu"] else (lambda s: s)
        for r in range(4):
            out.append(f"    dst[int2(p.x * 2 + {r & 1}, p.y * 2 + {r >> 1})] = {act(f'r{r}')};")
    out.append("}")
    return out


def main():
    src = sys.argv[1]
    dst = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(__file__), "..", "shaders", "artcnn.hlsl")
    layers = parse(open(src, encoding="utf-8").read())
    nweights = sum(len(t[2]) for L in layers for t in L["terms"]) + sum(4 * len(L["bias"]) for L in layers)
    lines = [
        f"// GENERATED by tools/artcnn_port.py from {os.path.basename(src)} - do not edit.",
        "// ArtCNN (c) 2024 Joao Chrisostomo, Kacper Michajlow, MIT license (https://github.com/Artoriuz/ArtCNN).",
        f"// {len(layers)} conv layers, {nweights} weights. RGBA8 src (w x h) -> luma -> CNN -> dst = src + (luma' - luma).",
        "// Root constant `layer` selects the pass; the C++ side (CsArtCnn) ping-pongs the feature textures and",
        "// bounds-clamps are edge-replicate (the GLSL's texelFetch out of range is undefined).",
        "Texture2D<float4>   src  : register(t0);   // layer 0: RGBA8 input; 1..6: feature map (2w x 2h RGBA16F)",
        "Texture2D<float4>   skip : register(t1);   // last layer: layer-0 features (long skip); else unused",
        "Texture2D<float4>   rgb  : register(t2);   // last layer: RGBA8 input; else unused",
        "RWTexture2D<float4> dst  : register(u0);   // feature map, or RGBA8 on the last layer",
        "cbuffer C : register(b0) { uint w, h, layer; };",
        "",
        "int2 Cl(int2 p) { return clamp(p, int2(0, 0), int2(w - 1, h - 1)); }",
        "float4 Fq(Texture2D<float4> t, int2 p, int q) { p = Cl(p); return t[int2(p.x * 2 + (q & 1), p.y * 2 + (q >> 1))]; }",
        f"float Yl(int2 p) {{ return dot(src[Cl(p)].rgb, {LUMA}); }}",
        "",
    ]
    for n, L in enumerate(layers):
        lines += emit_layer(n, L, n == len(layers) - 1)
        lines.append("")
    lines += [
        "[numthreads(8, 8, 1)]",
        "void CSMain(uint3 id : SV_DispatchThreadID)",
        "{",
        "    if (id.x >= w || id.y >= h) return;",
        "    const int2 p = int2(id.xy);",
        "    [branch] switch (layer)",
        "    {",
    ]
    for n in range(len(layers)):
        lines.append(f"    case {n}: L{n}(p); break;")
    lines += ["    }", "}", ""]
    with open(dst, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"{dst}: {len(layers)} layers, {nweights} weights")
    for L in layers:
        print(f"  {L['desc']}: bind {L['binds']}, {len(L['terms'])} terms, relu={L['relu']}")


if __name__ == "__main__":
    main()
